config/routes.rb
FamilySchool::Application.routes.draw do

 get '/' => "users#index"

 get '/signup' => "users#new"
  get '/login' => 'session#new'
  post '/login' => 'session#create'

  resources :users do
    resources :students do
       resources :incidents
      resources :infractions
    end
  end
end
#== Route Map
# Generated on 23 Oct 2013 21:14
#
#                       signup GET    /signup(.:format)                                                   users#new
#                        login GET    /login(.:format)                                                    session#new
#                              POST   /login(.:format)                                                    session#create
#       user_student_incidents GET    /users/:user_id/students/:student_id/incidents(.:format)            incidents#index
#                              POST   /users/:user_id/students/:student_id/incidents(.:format)            incidents#create
#    new_user_student_incident GET    /users/:user_id/students/:student_id/incidents/new(.:format)        incidents#new
#   edit_user_student_incident GET    /users/:user_id/students/:student_id/incidents/:id/edit(.:format)   incidents#edit
#        user_student_incident GET    /users/:user_id/students/:student_id/incidents/:id(.:format)        incidents#show
#                              PUT    /users/:user_id/students/:student_id/incidents/:id(.:format)        incidents#update
#                              DELETE /users/:user_id/students/:student_id/incidents/:id(.:format)        incidents#destroy
#     user_student_infractions GET    /users/:user_id/students/:student_id/infractions(.:format)          infractions#index
#                              POST   /users/:user_id/students/:student_id/infractions(.:format)          infractions#create
#  new_user_student_infraction GET    /users/:user_id/students/:student_id/infractions/new(.:format)      infractions#new
# edit_user_student_infraction GET    /users/:user_id/students/:student_id/infractions/:id/edit(.:format) infractions#edit
#      user_student_infraction GET    /users/:user_id/students/:student_id/infractions/:id(.:format)      infractions#show
#                              PUT    /users/:user_id/students/:student_id/infractions/:id(.:format)      infractions#update
#                              DELETE /users/:user_id/students/:student_id/infractions/:id(.:format)      infractions#destroy
#                user_students GET    /users/:user_id/students(.:format)                                  students#index
#                              POST   /users/:user_id/students(.:format)                                  students#create
#             new_user_student GET    /users/:user_id/students/new(.:format)                              students#new
#            edit_user_student GET    /users/:user_id/students/:id/edit(.:format)                         students#edit
#                 user_student GET    /users/:user_id/students/:id(.:format)                              students#show
#                              PUT    /users/:user_id/students/:id(.:format)                              students#update
#                              DELETE /users/:user_id/students/:id(.:format)                              students#destroy
#                        users GET    /users(.:format)                                                    users#index
#                              POST   /users(.:format)                                                    users#create
#                     new_user GET    /users/new(.:format)                                                users#new
#                    edit_user GET    /users/:id/edit(.:format)                                           users#edit
#                         user GET    /users/:id(.:format)                                                users#show
#                              PUT    /users/:id(.:format)                                                users#update
#                              DELETE /users/:id(.:format)                                                users#destroy

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User <ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation

  has_many :students
  has_secure_password

  validates :email, :password, :password_confirmation, :presence => true
  validates :email, :uniqueness => true
  validates :password, :password_confirmation, :length => { in: 3..20 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(login_path)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @student = Student.new
    @students = Student.all
  end

  def edit
    @user = User.find(params[:id])
    render :new
  end
end

app/views/users/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Family, School, Community-Based Connects</title>
  <meta name="description" content="">
  <meta name="author" content="">


<body>
<div class="wrapper-user">

 <h1> Any way the triangle turns will give each child a solid base for success! </h1>

  Please click 'Enter' to get started:

  <a href= "signup"> Enter </a>


</div>



</body>
</html>

app/views/users/new.html.erb
  <% if @user.errors.any? %>
  <ul>
    <% @user.errors.messages.each do |error, msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="container-image">
    <div class="login">
      <h1> Did you sign up already? <br/>Login below </h1>
      <%= flash[:notice] %>


      <%= form_tag('/login') do %>
      <%= label_tag :email %></br>
      <%= text_field_tag :email %></br>
      <%= label_tag :password %></br>
      <%= password_field_tag :password %></br>
      <%= submit_tag "Login" %>
      <% end %>
    </div>



    <div class="signup">
      <h1> Do you need to register? Register below </h1>

      <%= form_for(@user) do |f| %>
      <%= f.label :first_name %></br>
      <%= f.text_field :first_name %><br>
      <%= f.label :last_name %></br>
      <%= f.text_field :last_name %><br>
      <%= f.label :email %></br>
      <%= f.text_field :email %><br>
      <%= f.label :password %></br>
      <%= f.password_field :password %><br>

      <%= f.label :password_confirmation %></br>
      <%= f.password_field :password_confirmation %><br>
      <%= f.submit "Sign Up" %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div>
 <p><span> Dean <%= @user.last_name %>, </span>
  what would you like to do? </p>
</div>

<div class="container">
  <div class="student">
    <h1> Add a Student </h1>
    <ul>
      <li>
        <%= link_to "Click here", new_user_student_path(@user) %>
      </li>
    </ul>
  </div>


  <div class="signup">
    <h1> Pick a student to add an infraction to their profile:</h1>

      <% @students.each do |student| %>
        <%= link_to student.first_name , user_student_path(@user, student ) %>
      <% end %>
  </div>
</div>